/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoyageCharterRouteImport } from './routes/voyage-charter'
import { Route as TimeCharterRouteImport } from './routes/time-charter'
import { Route as IndexRouteImport } from './routes/index'

const VoyageCharterRoute = VoyageCharterRouteImport.update({
  id: '/voyage-charter',
  path: '/voyage-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeCharterRoute = TimeCharterRouteImport.update({
  id: '/time-charter',
  path: '/time-charter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/time-charter': typeof TimeCharterRoute
  '/voyage-charter': typeof VoyageCharterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/time-charter': typeof TimeCharterRoute
  '/voyage-charter': typeof VoyageCharterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/time-charter': typeof TimeCharterRoute
  '/voyage-charter': typeof VoyageCharterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/time-charter' | '/voyage-charter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/time-charter' | '/voyage-charter'
  id: '__root__' | '/' | '/time-charter' | '/voyage-charter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimeCharterRoute: typeof TimeCharterRoute
  VoyageCharterRoute: typeof VoyageCharterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voyage-charter': {
      id: '/voyage-charter'
      path: '/voyage-charter'
      fullPath: '/voyage-charter'
      preLoaderRoute: typeof VoyageCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-charter': {
      id: '/time-charter'
      path: '/time-charter'
      fullPath: '/time-charter'
      preLoaderRoute: typeof TimeCharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimeCharterRoute: TimeCharterRoute,
  VoyageCharterRoute: VoyageCharterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
